### PR TITLE
fixed language of new mailer

### PR DESCRIPTION
**Pull request by kennyparsons**
- Changed "You've just request the {Movie,TV Show} {Title} to 
"You've just requested a {Movie,TV Show}: {Title}

- This makes the verbiage clearer and the title/separation precise. An example would be:
`You've just requested a Movie: The Woman in the Window` which is clearer than the original: `You've just requested the Movie The Woman in the Window`

### CODE REVIEW

**Comment by AshDyson** [comment]
Please rebase to develop and I'll review it. Thanks

**Comment by ADRFranklin** [comment]
@kennyparsons Just need to know if you are still planning to work on this?

**Comment by kennyparsons** [comment]
@AshDyson @ADRFranklin rebased to develop

**Comment by ADRFranklin** [comment]
There are still conflicts with this PR, they would need to be sorted. 

Sorry I should of fixed this when I merged the dependabot stuff, I've been quite busy so didn't have time to fix it myself.

**Comment by ADRFranklin** [comment]
@kennyparsons I've fixed the issue in the develop branch, could you rollback your rebase on this branch?

**Pull request merged**
