### PR TITLE
Update Notification

### PR DESCRIPTION
**Pull request by davidjmorin**
Add thumbnail instead of image.

### CODE REVIEW

**Comment by AshDyson** [comment]
Please rebase to the develop branch and I can action this

**Comment by ADRFranklin** [comment]
@davidjmorin Are you still planning to rebase this, so we can review and merge it?

**Comment by davidjmorin** [comment]
> @davidjmorin Are you still planning to rebase this, so we can review and merge it?

I believe this was done already.  No?

**Comment by davidjmorin** [comment]
https://github.com/petio-team/petio/blob/develop/api/notifications/discord.js
This is showing changed in the dev branch

**Pull request closed without merging**
